blank_issues_enabled: false
contact_links:
  - name: Ask Hydrogram related questions
    url: https://stackoverflow.com/questions/tagged/hydrogram
    about: This place is only for reporting issues about Hydrogram. You can ask questions at StackOverflow.
  - name: Join the Telegram channel
    url: https://t.me/HydrogramNews
    about: Join the official channel and stay tuned for news, updates and announcements.
